# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FQfEiTAi3zRGY0rajPZL6BslIjIgvf8q
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('insurance.csv')

df

"""EDA"""

df.shape

df.head()

df.info()

df.describe()

#CHECK NULL VALUES
df.isnull().sum()

df.columns

#data visualization
numaric_columns =['age', 'bmi', 'children', 'charges']
for col in numaric_columns:
    plt.figure(figsize=(10,5))
    sns.histplot(df[col],kde = True, bins = 20)

sns.countplot(df['sex'])

sns.countplot(df['smoker'])

for col in numaric_columns:
  plt.figure(figsize=(10,5))
  sns.boxplot(x=df[col])

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True),annot=True)